// React Js
import * as React from "react";

// Next Js
import Head from "next/head";
import Image from "next/image";

// Material Ui
import Box from "@mui/material/Box";
import { ThemeProvider, createTheme } from "@mui/material/styles";
import { orange } from "@mui/material/colors";

// styles
import styles from "/styles/layout/layout.module.css";

// Components
import Navbar from "../navbar/miniDrawer";

interface Props {
  children: React.ReactNode;
}

let Layout = ({ children }: Props) => {
  let [mode, setMode] = React.useState("dark");
  const theme = createTheme({
    palette: {
      ...(mode === "dark" && {
        primary: {
          main: orange[200],
          light: "#fff",
        },
        text: {
          primary: "#fff",
          secondary: "#121212",
        },
        background: {
          default: "#121212",
        },
        divider: orange[100],
      }),
      ...(mode === "light" && {
        primary: {
          main: orange[500],
          light: "rgba(0, 0, 0, 0.87)",
        },
        text: {
          primary: "rgba(0, 0, 0, 0.87)",
          secondary: "#121212",
        },
        background: {
          default: "#fff",
        },
        divider: orange[500],
      }),
    },
  });
  return (
    <ThemeProvider theme={theme}>
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar>
        <Box
          className={styles.container}
          sx={{ bgcolor: "background.default" }}
        >
          {children}
        </Box>
        <Box
          className={styles.footer}
          sx={{ bgcolor: "background.default", color: "text.primary" }}
        >
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </Box>
      </Navbar>
    </ThemeProvider>
  );
};

export default Layout;
